%YAML:1.0

dataset.root_dir: /data/dataset/kitti_odometry/color/
dataset.sequence_num: 0

param.feature_num: 200
param.min_distance: 30
param.border_size: 1

camera.camera_num: 2
camera.height: 376
camera.width: 1241

camera.fx: 7.188560000000e+02
camera.fy: 7.188560000000e+02
camera.cx: 6.071928000000e+02
camera.cy: 1.852157000000e+02

camera.k1: 0.0
camera.k2: 0.0
camera.p1: 0.0
camera.p2: 0.0
camera.k3: 0.0
